# Generated by Django 5.0.6 on 2026-07-06 23:14

import accounts.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='半角英数字のみ、32字以下', max_length=32, unique=True, validators=[accounts.models.user_model.validate_halfwidth_name])),
                ('rate', models.IntegerField(default=1500, verbose_name='レート')),
                ('en', models.BigIntegerField(default=0, verbose_name='ゲーム内通貨')),
                ('tickets', models.IntegerField(default=0, verbose_name='購入チケット数')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時（ログインボーナス判定用）')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
            },
            managers=[
                ('objects', accounts.models.user_model.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('achievement_key', models.CharField(max_length=64)),
                ('grade', models.CharField(choices=[('BRONZE', '銅'), ('SILVER', '銀'), ('GOLD', '金')], default='BRONZE', max_length=10)),
                ('en', models.IntegerField(default=0, verbose_name='達成時に付与されるen')),
                ('achieve_bool', models.BooleanField(default=False, verbose_name='達成済みかどうか')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績',
                'db_table': 'achievement',
            },
        ),
    ]
