# Generated by Django 5.0.6 on 2026-07-06 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSkill',
            fields=[
                ('skill_id', models.CharField(help_text='例: boost_lap5', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('effect', models.TextField(help_text='効果の説明文')),
                ('flavor', models.TextField(blank=True, help_text='フレーバー文章')),
                ('trigger', models.CharField(help_text='発動条件（例: lap5_start, passive, race_start等）', max_length=64)),
                ('passive', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict, help_text='具体的な効果と数値')),
                ('price', models.IntegerField(default=15000)),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
                'db_table': 'car_skills',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('speed_scale', models.JSONField(default=list, help_text='ラップ毎の速度倍率配列')),
                ('battery_scale', models.JSONField(default=list, help_text='ラップ毎のバッテリー消費倍率配列')),
                ('color', models.CharField(default='#ffffff', help_text='UI表示色（例: #ff6633）', max_length=16)),
                ('pattern', models.CharField(default='lightning', help_text='車体マークパターン名', max_length=32)),
                ('mark_color', models.IntegerField(default=16777215, help_text='マーク色（0xRRGGBB整数）')),
            ],
            options={
                'verbose_name': '車種タイプ',
                'verbose_name_plural': '車種タイプ',
                'db_table': 'car_type',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('play_member', models.JSONField(help_text='参加者ID配列。Botの場合は"Bot1"等の名前を格納')),
                ('rank', models.JSONField(help_text='順位を記録（play_member順 or 別途順位配列）')),
                ('car_data', models.JSONField(help_text='順位順に車のIDを記録')),
                ('bet', models.JSONField(help_text='順位順の賭けの受け渡し結果')),
                ('rate', models.JSONField(help_text='レートの変動結果 {user_id: delta}')),
                ('race_seed', models.BigIntegerField(help_text='レース開始時にサーバーが払い出した乱数シード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, help_text='この結果を報告したホストのuser_id（不正調査用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_results', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='部屋削除後も記録は残すためSET_NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='rooms.room')),
            ],
            options={
                'verbose_name': 'レース結果',
                'verbose_name_plural': 'レース結果',
                'db_table': 'result',
                'ordering': ['-created_at'],
            },
        ),
    ]
