# Generated by Django 5.0.6 on 2026-07-06 23:14

import django.db.models.deletion
import rooms.models.room_model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(default=rooms.models.room_model.generate_room_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=64)),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, help_text='パス付き部屋用（null許容）', max_length=64, null=True)),
                ('status', models.CharField(choices=[('WAITING', '待機中'), ('RACING', 'レース中')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_list', models.JSONField(blank=True, default=list, help_text='現在のBotリスト（例: ["Bot1","Bot2"]）')),
                ('current_race_setup', models.JSONField(blank=True, help_text='race_consumer.send_race_setup()が生成した race_seed/car_configs/参加者対応表', null=True)),
                ('host_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL, verbose_name='ホストユーザー')),
            ],
            options={
                'verbose_name': '部屋',
                'verbose_name_plural': '部屋',
                'db_table': 'room',
            },
        ),
    ]
