# Generated by Django 5.0.6 on 2026-07-06 23:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color_code', models.CharField(help_text='例: #FF0000', max_length=7)),
                ('color_type', models.CharField(choices=[('COLOR1', 'ボディカラー'), ('COLOR2', 'アクセントカラー'), ('COLOR3', 'マークカラー')], max_length=10)),
                ('price', models.IntegerField(default=75000)),
            ],
            options={
                'verbose_name': 'カラー',
                'verbose_name_plural': 'カラー',
                'db_table': 'car_color',
                'unique_together': {('color_code', 'color_type')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preset_number', models.IntegerField(help_text='1〜4:初期プリセット / 5以降:購入制 / 99:現在使用中')),
                ('car_name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='車名は半角英数字・記号(_-.)のみ、32字以下で入力してください。', regex='^[A-Za-z0-9_\\-\\.]{1,32}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='game.cartype', verbose_name='戦略タイプ')),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.carskill', verbose_name='メインスキル')),
                ('sub_skill_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.carskill', verbose_name='サブスキル1')),
                ('sub_skill_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.carskill', verbose_name='サブスキル2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザー')),
                ('color_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garage.carcolor', verbose_name='ボディカラー')),
                ('color_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garage.carcolor', verbose_name='アクセントカラー')),
                ('color_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garage.carcolor', verbose_name='マークカラー')),
            ],
            options={
                'verbose_name': '車体',
                'verbose_name_plural': '車体',
                'db_table': 'car',
                'unique_together': {('user', 'preset_number')},
            },
        ),
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='garage.carcolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '所持カラー',
                'verbose_name_plural': '所持カラー',
                'db_table': 'user_color',
                'unique_together': {('user', 'color')},
            },
        ),
        migrations.CreateModel(
            name='UserPresetSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_number', models.IntegerField(help_text='開放したプリセット番号（5以降）')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プリセット枠',
                'verbose_name_plural': 'プリセット枠',
                'db_table': 'user_preset_slot',
                'unique_together': {('user', 'preset_number')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='game.carskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '所持スキル',
                'verbose_name_plural': '所持スキル',
                'db_table': 'user_skill',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
