# Generated by Django 5.0.6 on 2026-07-13 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementMaster',
            fields=[
                ('achievement_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('RACE', 'レース'), ('GARAGE', 'ガレージ'), ('ECONOMY', '経済')], default='RACE', max_length=16)),
                ('metric', models.CharField(help_text='win_count / win_count_early / win_count_steady / win_count_late / rank34_count / races_played / colors_owned_pct / skills_owned_pct / rate / en_holding など。進捗更新・判定ロジックがこの値で分岐する。', max_length=32)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '実績定義',
                'verbose_name_plural': '実績定義',
                'db_table': 'achievement_master',
                'ordering': ['sort_order', 'achievement_key'],
            },
        ),
        migrations.CreateModel(
            name='AchievementTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('BRONZE', '銅'), ('SILVER', '銀'), ('GOLD', '金')], max_length=10)),
                ('threshold', models.FloatField(help_text='解除に必要な値（メトリクスにより回数・%・レート値等）')),
                ('en_reward', models.BigIntegerField(help_text='達成時に貰えるen（銅=30000/銀=100000/金=1000000）')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='myroom.achievementmaster')),
            ],
            options={
                'verbose_name': '実績段階',
                'verbose_name_plural': '実績段階',
                'db_table': 'achievement_tier',
                'unique_together': {('achievement', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='myroom.achievementmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '実績進捗',
                'verbose_name_plural': '実績進捗',
                'db_table': 'user_achievement_progress',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('en_granted', models.BigIntegerField(default=0)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='myroom.achievementtier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '実績達成履歴',
                'verbose_name_plural': '実績達成履歴',
                'db_table': 'user_achievement_unlock',
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'tier')},
            },
        ),
    ]
